export interface RecintosInterfaz {
  idRec:any,
  nombre:any,
  temp_verano:any,
  temp_invierno:any,
  hr_verano:any,
  hr_invierno:any,
  ida:any,
  nivel_filtro:any,
  largo:any,
  ancho:any,
  alto:any,
  volumen:any,
  cerramiento1: any,
  cerramiento2:any,
  cerramiento3:any,
  cerramiento4:any,
  cubierta:any, //TEcho interior o exterior
  color_cubierta:any, //Color techo
  tempTechoVer:any,
  tempTechoInv:any,
  supTecho:any,
  contieneVidrioTecho:any,
  superficieVidrioTecho:any,
  tipoVidrio:any,
  contienePuertasTecho:any,
  superficiePuertasTecho:any,
  suelo:any,
  supeSuelo:any,
  numPersonas:any,
  cargaSensible:any,
  cargaLatente:any,
  caudalIda:any,
  caudalAire:any,
  lamparas:any, //Fluorescente o Led
  potenciaIluminacion:any,
  mayoracion:any,
  equipos:any,
  cargaSensibleRadiacionVidrio:any,
  cargaSensibleCerramientos:any, 
  cargaSensibleAire:any,
  cargaSensibleOcupacion:any,
  cargaSensibleIluminacion:any, 
  cargaSensibleEquipamiento:any,
  cargaTotalSensibleRefrigeracion:any,
  cargaLatenteAire:any,
  cargaLatenteOcupacion:any,
  cargaTotalLatenteRefrigeracion:any,
  potenciaRefrigeracion:any,
  cargaSensibleCerramientosInv:any, 
  cargaSensibleAireInv:any,
  cargaTotalSensibleCalefaccion:any, 
  potenciaCalefaccion:any
  
}
